### ISSUE TITLE
Air 3

### ISSUE THREAD

**Issue by 36162** [YarosMallorca/dji-o3-fcc-hack#1]

**Comment by YarosMallorca** [comment]
@36162 This only supports DJI FPV systems (Avata 2, O3 Air Unit...)
For now no other support is planned.

**Comment by 36162** [comment]
Virker denne her ikke til Sir 3.   ??    Da jeg ikke kan finde ud af at
installere det på min telefon. ??       Kan i hjælpe mig med at installere
den nu hvor jeg har købt den på forhånd tak

Sendt fra Gmail Mobil


ons. 24. jul. 2024 kl. 21.51 skrev Yaros ***@***.***>:

**Comment by YarosMallorca** [comment]
@36162 No.
As mentioned before **THIS ONLY WORKS ON FPV DJI DRONES** not Mavics.

**Comment by 36162** [comment]
Yes.  Air 3.  Is a fpv drone right?

**Comment by YarosMallorca** [comment]
@36162 No. Air 3 isn't an FPV drone.

The only devices that this site supports is:
- DJI Avata
- DJI Avata 2
- DJI FPV
- DJI O3 Air Unit
- DJI FPV Air Unit
- Caddx Vista

with the following goggles:
- DJI Goggles 2
- DJI Goggles Integra
- DJI Goggles 3 (not tested)
